# Generated by Django 5.1.5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0004_dnsfilterlist_recommended'),
    ]

    operations = [
        migrations.AddField(
            model_name='statichost',
            name='is_wildcard',
            field=models.BooleanField(
                default=False,
                help_text='If set, this domain and all its subdomains resolve to the given IP (e.g. example.com matches *.example.com)',
            ),
        ),
    ]
